### ISSUE TITLE
Offline update-all script fails

### ISSUE THREAD

**Issue by scmbradley** [chubin/cheat.sh#291]
Running the script to update the offline cht.sh yields the following error:

```
Traceback (most recent call last):
  File "/home/scmb/.cheat.sh/lib/fetch.py", line 223, in <module>
    main(sys.argv[1:])
  File "/home/scmb/.cheat.sh/lib/fetch.py", line 217, in main
    update_all()
  File "/home/scmb/.cheat.sh/lib/fetch.py", line 172, in update_all
    _update_adapter(adptr)
  File "/home/scmb/.cheat.sh/lib/fetch.py", line 144, in _update_adapter
    entries = adptr.get_updates_list(updates)
  File "/home/scmb/.cheat.sh/lib/adapter/tldr.py", line 105, in get_updates_list
    if entry.endswith(ext):
TypeError: endswith first arg must be bytes or a tuple of bytes, not str

```
with `python --version` 3.8.5

**Comment by chubin** [comment]
Should be fixed now; please update and test. Thank you for reporting!

**Comment by scmbradley** [comment]
I'm now getting a different error when I try to update (after deleting `.cheat.sh` and running `cht.sh --standalone-install` again:

```
[Adapter: late.nz (Latenz)] Entries to be updated: 5
+ ivalidating LICENSE
Traceback (most recent call last):
  File "/home/scmb/.cheat.sh/ve/lib/python3.8/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
  File "/home/scmb/.cheat.sh/ve/lib/python3.8/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/home/scmb/.cheat.sh/ve/lib/python3.8/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/scmb/.cheat.sh/lib/fetch.py", line 224, in <module>
    main(sys.argv[1:])
  File "/home/scmb/.cheat.sh/lib/fetch.py", line 218, in main
    update_all()
  File "/home/scmb/.cheat.sh/lib/fetch.py", line 173, in update_all
    _update_adapter(adptr)
  File "/home/scmb/.cheat.sh/lib/fetch.py", line 151, in _update_adapter
    cache.delete(entry)
  File "/home/scmb/.cheat.sh/lib/cache.py", line 71, in delete
    _REDIS.delete(key)
  File "/home/scmb/.cheat.sh/ve/lib/python3.8/site-packages/redis/client.py", line 1567, in delete
    return self.execute_command('DEL', *names)
  File "/home/scmb/.cheat.sh/ve/lib/python3.8/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/home/scmb/.cheat.sh/ve/lib/python3.8/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/home/scmb/.cheat.sh/ve/lib/python3.8/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.

```

Also, I got this warning while doing the standalone install. (I guess this is a different issue)

```
>> Installing python requirements into the virtual environment 
WARNING: You are using pip version 21.0.1; however, version 21.1 is available.
You should consider upgrading via the '/home/scmb/.cheat.sh/ve/bin/python -m pip install --upgrade pip' command.
```

**Comment by chubin** [comment]
This is because you don't have redis locally, and it is configured by default as the cache layer.
You can try to set:
```
export CHEATSH_CACHE_TYPE=none
```

pip version warning is nothing special, it just means that your local pip installation is a little bit outdated. If you want to upgrade it, run: 

```
sudo pip install --upgrade pip
```

(but after some time it will become outdated again)

**Comment by scmbradley** [comment]
OK thanks. I only mentioned the pip version thing because I don't normally get the error and so I wondered whether it was an issue with the virtual environment that cht.sh sets up.

Perhaps the instructions for standalone installation should mention the redis/ `CHEATSH_CACHE_TYPE=none` issue?

**Comment by chubin** [comment]
A good point! Added

**Comment by abitrolly** [comment]
Having Redis cache by default doesn't seem useful as user installations do not need that kind of performance, and may use some other cache, like SQLite or no cache at all.

**Comment by chubin** [comment]
Fully agree with you. File-based cache would be probably the best alternative here,
but by default, I believe, caching should be switched fully off
