### ISSUE TITLE
faild build self-host image with docker

### ISSUE THREAD

**Issue by tomasWade** [chubin/cheat.sh#307]
hi
 I want to build a self-host image so I run : 
```bash
docker-compose build
```
but I got error like this :

```
Fetching [Adapter: cheat (Cheat)]...Done
Fetching [Adapter: late.nz (Latenz)]...Traceback (most recent call last):
  File "lib/fetch.py", line 224, in <module>
    main(sys.argv[1:])
  File "lib/fetch.py", line 214, in main
    fetch_all()
  File "lib/fetch.py", line 102, in fetch_all
    _fetch_locations(known_location)
  File "lib/fetch.py", line 66, in _fetch_locations
    sys.stdout.write("\nERROR:\n---\n" + output)
TypeError: can only concatenate str (not "bytes") to str
ERROR: Service 'app' failed to build: The command '/bin/sh -c mkdir -p /root/.cheat.sh/log/     && python3 lib/fetch.py fetch-all' returned a non-zero code: 1
```

It looks like something wrong with python version. but I do not know how to fix it.

**Comment by abitrolly** [comment]
Most likely the network failure or `late.nz` was down.

#309 should fix that.

**Comment by abitrolly** [comment]
@tomasWade can you check that the latest code works for you? There are no issues now on several other machines.

**Comment by abitrolly** [comment]
This is now fixed for good. Feel free to open another issue if it persists.
