### ISSUE TITLE
standalone mode failed

### ISSUE THREAD

**Issue by realtica** [chubin/cheat.sh#370]
Python 3.10.2
pip 22.0.2

I've installed all this:

`https://raw.githubusercontent.com/chubin/cheat.sh/46d1a5f73c6b88da15d809154245dbf234e9479e/requirements.txt`
This is the error with mode=auto

```
Traceback (most recent call last):
  File "/home/realtica/.cheat.sh/lib/standalone.py", line 17, in <module>
    import cheat_wrapper
  File "/home/realtica/.cheat.sh/lib/cheat_wrapper.py", line 14, in <module>
    from routing import get_answers, get_topics_list
  File "/home/realtica/.cheat.sh/lib/routing.py", line 15, in <module>
    import adapter.cheat_sheets
  File "/home/realtica/.cheat.sh/lib/adapter/__init__.py", line 18, in <module>
    from . import *
  File "/home/realtica/.cheat.sh/lib/adapter/question.py", line 15, in <module>
    from polyglot.detect import Detector
  File "/home/realtica/.cheat.sh/ve/lib/python3.9/site-packages/polyglot/detect/__init__.py", line 1, in <module>
    from .base import Detector, Language
  File "/home/realtica/.cheat.sh/ve/lib/python3.9/site-packages/polyglot/detect/base.py", line 11, in <module>
    from icu import Locale
  File "/home/realtica/.cheat.sh/ve/lib/python3.9/site-packages/icu/__init__.py", line 37, in <module>
    from ._icu_ import *
ImportError: libicui18n.so.71: cannot open shared object file: No such file or directory
```

**Comment by abitrolly** [comment]
This library is supposed to do language detection https://github.com/chubin/cheat.sh/issues/259 but the feature doesn't work for years. Maybe we should just remove it for now.

**Comment by realtica** [comment]
> This library is supposed to do language detection #259 but the feature doesn't work for years. Maybe we should just remove it for now.

I need to install the standalone mode, how can I remove the language feature?

**Comment by abitrolly** [comment]
@realtica with a patch like this https://github.com/chubin/cheat.sh/pull/372

**Comment by evrial** [comment]
Until @chubin merged into master, fix cht.sh, find: `git clone blablabla`, add: `git clone -b remove-language-support blablabla`
