### ISSUE TITLE
Why does standalone install require Python2?

### ISSUE THREAD

**Issue by hackdefendr** [chubin/cheat.sh#371]
Python2 on Mac OS has been fully removed at the system level and cannot be installed via Homebrew anymore. I know about #327 and that #368 is waiting for approval to work around it, but Python2 is in fact uninstallable on MacOS, so unless the core dependency on Python2 is updated we will still not be able to install or even build local versions on Macs.

**Comment by abitrolly** [comment]
I am not on Mac, so.. when this happens and what do you see?

**Comment by hackdefendr** [comment]
Initially I see an error about python not existing, I guessed it meant the symlink to the Python2 binary. I tried to fix this by creating the symlink pointing to the Python3 binary. Then I tried again and got the crash with icu, which #368 works around.

I did manage to compile ICU 72 on my M1 Mac, but cht.sh still crashes when it tries to pull down the cheat sheets from the repository. Here is the full output minus the Test output:

```
macbookpro:~ jsingleton$ cht.sh --standalone-install
Where should cheat.sh be installed [/Users/jsingleton/.cheat.sh]?

>> Cloning cheat.sh locally
Cloning into '/Users/jsingleton/.cheat.sh'...
remote: Enumerating objects: 3785, done.
remote: Counting objects: 100% (248/248), done.
remote: Compressing objects: 100% (122/122), done.
remote: Total 3785 (delta 136), reused 211 (delta 123), pack-reused 3537
Receiving objects: 100% (3785/3785), 4.46 MiB | 7.20 MiB/s, done.
Resolving deltas: 100% (2363/2363), done.

>> Creating virtual environment
created virtual environment CPython3.11.0.final.0-64 in 203ms
  creator CPython3Posix(dest=/Users/jsingleton/.cheat.sh/ve, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/Users/jsingleton/Library/Application Support/virtualenv)
    added seed packages: pip==22.3.1, setuptools==65.6.3, wheel==0.38.4
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

>> Installing python requirements into the virtual environment
      40 dependencies were successfully installed

>> Fetching the upstream cheat sheets repositories
Traceback (most recent call last):
  File "/Users/jsingleton/.cheat.sh/lib/fetch.py", line 22, in <module>
    import adapter
  File "/Users/jsingleton/.cheat.sh/lib/adapter/__init__.py", line 18, in <module>
    from . import *
  File "/Users/jsingleton/.cheat.sh/lib/adapter/question.py", line 15, in <module>
    from polyglot.detect import Detector
  File "/Users/jsingleton/.cheat.sh/ve/lib/python3.11/site-packages/polyglot/detect/__init__.py", line 1, in <module>
    from .base import Detector, Language
  File "/Users/jsingleton/.cheat.sh/ve/lib/python3.11/site-packages/polyglot/detect/base.py", line 11, in <module>
    from icu import Locale
  File "/Users/jsingleton/.cheat.sh/ve/lib/python3.11/site-packages/icu/__init__.py", line 37, in <module>
    from ._icu_ import *
ImportError: dlopen(/Users/jsingleton/.cheat.sh/ve/lib/python3.11/site-packages/icu/_icu_.cpython-311-darwin.so, 0x0002): Library not loaded: libicui18n.72.dylib
  Referenced from: <A6EB7F0C-706E-39CC-88C4-96B8B8B3B4BD> /Users/jsingleton/.cheat.sh/ve/lib/python3.11/site-packages/icu/_icu_.cpython-311-darwin.so
  Reason: tried: 'libicui18n.72.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibicui18n.72.dylib' (no such file), 'libicui18n.72.dylib' (no such file), '/usr/local/lib/libicui18n.72.dylib' (no such file), '/usr/lib/libicui18n.72.dylib' (no such file, not in dyld cache), '/Users/jsingleton/.cheat.sh/libicui18n.72.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/jsingleton/.cheat.sh/libicui18n.72.dylib' (no such file), '/Users/jsingleton/.cheat.sh/libicui18n.72.dylib' (no such file), '/usr/local/lib/libicui18n.72.dylib' (no such file), '/usr/lib/libicui18n.72.dylib' (no such file, not in dyld cache)

>> Running self-tests
...
```
Question, are there hardcoded paths in cht.sh? If yes, `/opt/homebrew/{bin,sbin}` should be added for M1/M2 Macs running HomeBrew. 

Thanks for looking at this. I'm here to test and provide logs for the M1/M2 Mac support.

**Comment by user-xffdsjkh** [comment]
How can I get my phone unlocked? The call widget controls all calls.
Neighbors are impersonating therapists at the crisis center and deputies
when I call sheriff's. Calls intercepted and blocked from my kids &
doctors, etc. Recorded & invaded. Homes been automated, drones in my home
all the time. Cops are worthless unless I have video. I had some and it was
modified as I watched it. This video is on a non active phone too. He's
controlling all my calls. I'm at a loss. He broke my car attempting to
automate and there's cams & sensors everywhere.  And the entire
neighborhood seems to know where I am. No idea how many have access to
home, it gets broken into every time I leave the house. I can read the
system & event logs but I don't know how to write code or even where to
start.

Jennifer E. Cook

**Comment by abitrolly** [comment]
Wow. I can just remove comments here. Nice. :D Well, not really, but whatever.

**Comment by abitrolly** [comment]
@hackdefendr try this route https://github.com/chubin/cheat.sh/pull/372 - should get rid of the ICU.

**Comment by hackdefendr** [comment]
Hi hi, 
I just am getting to this. Let me pull that branch and see how it goes. 
I will update this comment with details.
